# Generated by Django 4.2.3 on 2023-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0002_alter_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
