# Generated by Django 4.2.3 on 2023-07-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0002_remove_property_maintanance_charge_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='maintanance_charge_per_month',
            field=models.IntegerField(default=0),
        ),
    ]
