# Generated by Django 4.2.3 on 2023-07-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0004_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
    ]
