# Generated by Django 4.2.3 on 2023-07-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0005_remove_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
