# Generated by Django 4.2.3 on 2023-07-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0006_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
