# Generated by Django 4.2.3 on 2023-07-28 11:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0008_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description1',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
