# Generated by Django 4.2.3 on 2023-07-28 11:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0009_blog_description1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description1',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
