# Generated by Django 4.2.3 on 2023-07-28 13:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0011_blog_description1_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description1',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
